name: timv-app
services:
- name: web
  source_dir: /
  github:
    repo: twoje-repo
    branch: main
  run_command: streamlit run app.py --server.port=8080 --server.address=0.0.0.0 --server.headless=true
  environment_slug: python
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /
    timeout_seconds: 60
    period_seconds: 10
    failure_threshold: 3