# .streamlit/config.toml
[server]
headless = true
address = "0.0.0.0"
port = 8501

# Bez konfliktu z XSRF – zostaw CORS włączony w PROD,
# chyba że wiesz, co robisz (reverse proxy itp.).
enableCORS = true
enableXsrfProtection = true

[client]
# Przydatne przy dłuższych jobach
showErrorDetails = true
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
# Pozwala na ponowne uruchomienie z pamięcią stanu sesji
magicEnabled = true
fastReruns = true

[logger]
level = "info"
